#配置端口号
server:
  port: 9999

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xdb?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: k2720668823
#  redis:
#    #端口号
#    port: 6379
#    #连接地址(Linux中安装，则输入Linux的地址)
#    host: 192.168.195.128
#    #密码
#    password: k2720668823
#    #数据库索引
#    database: 0
#    #连接超时时间（毫秒）
#    connect-timeout: 1800000
#    lettuce:
#      pool:
#        #连接池最大连接数
#        max-active: 20
#    jedis:
#      pool:
#        #最大阻塞等待时间（负数表示没有限制）
#        max-wait: -1
#        #连接池中的最大空闲连接
#        max-idle: 5
#        #连接池中的最小空闲连接
#        min-idle: 0

#日志信息
logging:
  level:
    com.shengming: debug
mybatis-plus:
  global-config:
      db-config:
        logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)